const board_1 = 'WWWWWWWWGWGWWGWWWWWWWWWWWWGWWWWWWWWG';
const board_2 = 'WWWGWWWWWWWWWGWWGWWWWGWWWWWWWWWWGWWW';
const board_3 = 'WWWWGWWGWWWWWWWGWWWWWWWWWGWWWWWWWGWW';
const board_4 = 'WWWWWWWGWWWWWWWWGWGWWWWWWWWGWWWWGWWW';
const boards = [board_1, board_2, board_3, board_4]


const board_1_solve = [
    "RRWPPWRRGWGWPGWWBBWWWWBBWWGWBBPWWWWG",
    "WWWPPWWWGWGWPGRRBBWWRRBBWWGWBBPWWWWG",
    "RRWWWWRRGPGWWGWBBPWWWBBWWWGBBWWWWPPG",
    "WWWWWWWWGPGWWGWBBPRRWBBWRRGBBWWWWPPG",
    "RRWWWPRRGWGWWGWPPWWWPBBWWWGBBWWWWBBG",
    "WWWWWPWWGWGWWGWPPWRRPBBWRRGBBWWWWBBG",

    "WWWPPWWWGWGWPGWBBBRRWBBBRRGWWWPWWWWG",
    "WWWPPWWWGWGWPGWBBBWWWBBBWWGRRWPWWRRG",
    "RRWWWPRRGWGWWGWPPWWWPBBBWWGBBBWWWWWG",
    "WWWWWPWWGWGWWGWPPWWWPBBBRRGBBBRRWWWG",
    "RRPWWWRRGWGPWGBBBWWWBBBWWWGWWPWWPWWG",
    "WWPWWWWWGWGPWGBBBWWWBBBWRRGWWPRRPWWG",

    "WWPWWWWWGWGPWGWWWWBBWWWWBBGRRPBBPRRG",
    "WWPWWWWWGWGPWGWWRRBBWWRRBBGWWPBBPWWG",
    "WWWWWWWWGPGWWGWWWPBBWWRRBBGWRRBBWPPG",
    "WWWWWWWWGPGWWGRRWPBBRRWWBBGWWWBBWPPG"
]

const board_2_solve = [
    "BBBGRRBBBWRRWWWPGWPWWGWWWWPWWWWWGPWW",
    "BBBGWWBBBWWWWGWPGWPWWGWWWWPWRRWWGPRR",
    "BBBGWWBBBWPWWGPWGWWWPGPWRRWWWWRRGWWW",
    "BBBGWWBBBWPWWGPWGWWWPGPWWWWRRWWWGRRW",

    "WWWGWWWWWWWWWGWPGWPWWGBBRRPWBBRRGPBB",
    "WRRGWWWRRWWWWGWPGWPWWGBBWWPWBBWWGPBB",
    "WPWGWWPWPWWWWGWWGPWRRGBBWRRWBBWWGWBB",
    "WPWGRRPWPWRRWGWWGPWWWGBBWWWWBBWWGWBB",

    "WPWGRRPWPWRRWGWWGPWWWGWWWWWBBBWWGBBB",
    "WPWGWWPWPWWWWGWWGPWWWGWWRRWBBBRRGBBB",

    "RRWGWWRRWWPWWGPWGWBBPGPWBBWWWWBBGWWW",
    "WWWGWWWWWWPWWGPWGWBBPGPWBBWWRRBBGWRR",
    "WWPGWPWWRRWWPGRRGWBBWGWWBBWWWWBBGWWP",
    "WWPGWPWWWWWWPGWWGWBBWGRRBBWWRRBBGWWP",

    "RRPGWPRRWWWWPGWWGWBBBGWWBBBWWWWWGWWP",
    "WWPGWPWWWWWWPGWWGWBBBGWWBBBRRWWWGRRP"
]
const board_3_solve = [
    "PWWWGWWGWWBBRRWGBBRRWPBBWGWPWWWPWGWW",
    "PWWWGWWGWWBBWWWGBBWWWPBBWGWPRRWPWGRR",

    "WWWWGWWGPWWWRRWGBBRRWWBBPGWWBBWWWGPP",
    "WWWWGWWGPWWWWWWGBBWWRRBBPGRRBBWWWGPP",

    "WWRRGWPGRRPWWWWGWPWWWWBBWGPWBBWWWGBB",
    "WWWWGWPGWWPWWRRGWPWRRWBBWGPWBBWWWGBB",
    "WPWWGPWGWWWWWWPGWWWWRRBBWGRRBBPWWGBB",
    "WPWWGPWGWWWWRRPGWWRRWWBBWGWWBBPWWGBB",

    "WWRRGWPGRRPWWWWGWPWWWBBBWGPBBBWWWGWW",
    "WWWWGWPGWWPWRRWGWPRRWBBBWGPBBBWWWGWW",
    "WWWWGWWGPWWWWRRGWWWRRBBBPGWBBBWWWGPP",
    "WWWWGWWGPWRRWWWGRRWWWBBBPGWBBBWWWGPP",

    "WPRRGPWGRRWWWWPGWWWWBBBWWGBBBWPWWGWW",
    "WPWWGPWGWWRRWWPGRRWWBBBWWGBBBWPWWGWW",

    "PWRRGWWGRRWWBBBGWWBBBPWWWGWPWWWPWGWW"
]
const board_4_solve = [
    "WWBBBWWGBBBPWWRRGWGWRRWWPWWGWWWPGWPW",
    "WWBBBWWGBBBPWWWWGWGRRWWWPRRGWWWPGWPW",

    "PWWBBBWGWBBBWWWPGWGWWPRRWWWGRRWWGWWP",
    "PWWBBBWGWBBBWWWPGWGWWPWWRRWGWWRRGWWP",

    "WPBBRRWGBBRRWPBBGPGWWWWWWWPGWWWWGWWW",
    "WPBBWWWGBBWWWPBBGPGWWWWWRRPGWWRRGWWW",

    "WWPPWWWGBBWWWWBBGWGWBBWPWWWGRRWWGPRR",
    "WWPPWWWGBBWWWWBBGWGWBBWPRRWGWWRRGPWW",

    "WPRRWWWGRRWWWPWWGPGWWWBBWWPGBBWWGWBB",
    "WPWWRRWGWWRRWPWWGPGWWWBBWWPGBBWWGWBB",

    "PWRRWWWGRRWWWBBPGWGBBPWWWBBGWWWWGWWP",
    "PWWWWWWGWWWWWBBPGWGBBPRRWBBGRRWWGWWP",

    "WWRRWWWGRRWPWBBBGWGBBBWWPWWGWWWPGWPW",
    "WWWWWWWGWWWPWBBBGWGBBBRRPWWGRRWPGWPW",
    "WWPPRRWGWWRRWBBBGWGBBBWPWWWGWWWWGPWW",
    "WWPPWWWGWWWWWBBBGWGBBBWPWWWGRRWWGPRR",
]

const solved_boards = [board_1_solve, board_2_solve, board_3_solve, board_4_solve];
